### ISSUE TITLE
Implement mouse lock for Mac, Windows, and Web. Remove set_mouse_position.

### ISSUE THREAD

**Issue by kettle11** [kettle11/kapp#1]
set_mouse_position should be implemented here:
https://github.com/kettle11/kettlewin/blob/e0bb32b4e9083493bafcc53e5e97f00a24978536/platforms/macos/src/application_mac.rs#L259

The function accepts an x and y value expressed in physical screen coordinates. 

The coordinates should be converted to the appropriate coordinate space for the mouse's *current* screen.

This function call should only move a mouse within the current screen, which is what most games would need.

**Comment by kettle11** [comment]
Web only allows for locking the cursor position, not setting it, and that seems reasonable. `kapp` should implement a cross-platform mouse lock and still produce mouse-delta events. This would allow for proper FPS-style controls.

**Comment by kettle11** [comment]
- [x] Mac

- [ ] Windows

- [ ] Web

**Comment by lunabunn** [comment]
fa32eb7 implements this for web.

**Comment by kettle11** [comment]
Worth noting here: An event might also need to be issued to indicate that the mouse lock has ended, because on web it's possible for the user to cancel the mouse lock. 

In an FPS you wouldn't want the camera controls to stay enabled then.

But that can be deferred until someone has a need for such an event.

**Comment by kettle11** [comment]
Fixed in: https://github.com/kettle11/kapp/commit/0bd0d994db57a8ed13d85d1de3b57a7468b13d9c
