### ISSUE TITLE
Implement double click for Web and Windows

### ISSUE THREAD

**Issue by kettle11** [kettle11/kapp#21]
- [x] Windows (However no "Double Click Up" event is sent)
- [ ] Web

Note that double click on web by default triggers on the second up, which is different than other platforms. Perhaps this should be reconciled.

**Comment by lunabunn** [comment]
We could fake it on web with a timer between clicks, but that would be bad for accessibility (the specs for dblclick do not define the maximum delay between clicks; it's impl specific and any "hack" would be risky) so I don't see a real way to get consistent behaviour.

**Comment by kettle11** [comment]
Yeah, it's probably fine to implement the double-click event for Web in the most straightforward way and just document any inconsistency.

**Comment by lunabunn** [comment]
If Windows only hands you events for double click down and web only hands you events for double click up, should `DoubleClickDown` and `MouseButtonDoubleClickUp` (sidenote, those are some oddly named enum variants 👅 ) perhaps be merged? From like, my 5-second test, mouse click up seems to be the standard behaviour on OSX when launching applications, opening files, etc. so we could just fire on release on OSX if the two events were to be merged into a single `DoubleClick` event.

**Comment by kettle11** [comment]
Yeah that seems like a good breakdown. `DoubleClick` looks nicer and is easier to use in most scenarios. The enum variant can be commented with the platform differences.

However after writing that last sentence I just spent a few minutes trying to remember why I wanted both "Down" and "Up" for double-click and I did remember. I was implementing a 2D polygon editor before and I looked to Figma for inspiration. When selecting nodes in Figma's polygon their double-click responds on the second down instead of up, making it feel a little bit more responsive.

After a bit more research something I found for Web that I must have missed before. `Mousedown` and `MouseUp` events report their number of clicks: https://developer.mozilla.org/en-US/docs/Web/API/UIEvent/detail

This could be used to make Web behave the same as the other platforms. So it'd be possible to make all platforms report `DoubleClickUp` at least. But then, as you pointed out, that would make it harder to match the standard system behavior on MacOS at least. 

Given the various trade-offs maybe what's best is to have a simple `DoubleClick` that triggers on double-click up and is the same across Mac / Windows / Web. What do you think?

**Comment by lunabunn** [comment]
IMHO `DoubleClick` should be double click *down* on Windows, because that's what's reported by `WM_LBUTTONDBLCLK`. On Mac and Web, double click up makes sense because that's the default behaviour. If necessary, we could also implement `DoubleClickDown` and `DoubleClickUp` for each platform separately?

**Comment by lunabunn** [comment]
Have verified that on web, checking for `e == 2` in `mousedown` works perfectly for `DoubleClickDown` behaviour.

**Comment by kettle11** [comment]
> Given the various trade-offs maybe what's best is to have a simple DoubleClick that triggers on double-click up and is the same across Mac / Windows / Web. 

I meant to say on DoubleClick down, not up. 😅

I like what you've proposed in your latest response. It provides a helpful default and yet still allows the more specific behavior if needed. Sounds great!
