### ISSUE TITLE
Add 'maximum_size' to window builder

### ISSUE THREAD

**Issue by kettle11** [kettle11/kapp#22]
Presumably web will just not handle a 'maximum' window size, but it should be possible for Windows and Mac.

**Comment by kettle11** [comment]
Implemented for Mac in https://github.com/kettle11/kapp/commit/66409b285fc1bc124fc2f59ec886f6569ad9eb0c

**Comment by lunabunn** [comment]
Ready for close? Only remaining issue seems to be tracked by #61

**Comment by kettle11** [comment]
Yup! Forgot to close yesterday.
