### ISSUE TITLE
Actually use version numbers for GL context creation

### ISSUE THREAD

**Issue by kettle11** [kettle11/kapp#28]
The GLContext creation part of this crate is mostly incomplete, a good first step would be to allow the GL version to be specified.

**Comment by lunabunn** [comment]
If we pass in a major and minor version upon context creation, are we okay with just ignoring them for web?

**Comment by kettle11** [comment]
Yup!

Also a word of warning: in general the GL Context crate is less polished than the rest of `kapp`. I got it to the point where it worked for me, but didn't go much further.

If you see anything you think could be improved feel free to open an issue or pull request.

**Comment by kettle11** [comment]
These flags still need to be set properly on Mac.
