### ISSUE TITLE
Project Goals for Portability

### ISSUE THREAD

**Issue by lunabunn** [kettle11/kapp#52]
The README states:
> kApp strives to be unsurprising, quick to build, and straightforward to maintain.

Now, of course at this point in time `kapp` is nowhere near as production-ready/battletested as SDL2, winit/glutin, etc. However, to me it's unclear if it's a project goal in the first place to eventually be production-usable. To me, an *unsurprising*, *production-usable* windowing library is one that "just works" on Windows XP+ & OSX Mountain Lion+ or something along those lines. Will kapp ever fit that bill or does it have a smaller scope in mind? Clarifications in the README would be appreciated.

**Comment by kettle11** [comment]
Good question. 

I think it is an *eventual* goal to be production-ready, but it's a lot of work so I've spread it out over a long period of time. 

>  on Windows XP+ & OSX Mountain Lion+ or something along those lines

To keep the scope manageable I've only worked to support the latest versions of each OS. My goal has been to get `kapp` to a point of consistency and quality across the latest Windows / latest MacOS / and modern browsers, and then evaluate other platforms. You're right that should be called out in the README.

However if issues come up for older versions that are trivially fixed (without massive hacks or code complications) then I have no opposition to fixing them.

**Comment by lunabunn** [comment]
Makes sense, those are fair goals! Love the work you've been doing and super hyped to use it for a lil' 2d game engine deal I'm planning on. Keep up the good work 👍 

Will leave this open as a reminder that the README might need some more info. Please feel free to close it whenever as you see fit.

**Comment by kettle11** [comment]
> Love the work you've been doing and super hyped to use it for a lil' 2d game engine deal I'm planning on.

I'm super excited to see that! It's really gratifying to hear that my work is helpful to others, especially since I've been chipping away at this relatively incognito for a while.

Thanks for the kind words!
