### ISSUE TITLE
Why 2 dummy windows for GL Context creation? (Windows)

### ISSUE THREAD

**Issue by lunabunn** [kettle11/kapp#53]
https://github.com/kettle11/kapp/blob/2b236c6b53d042afed6cdcb448121eb905fca624/gl_context/src/windows/mod.rs#L294-L378

Why exactly are we creating a second dummy window here?

**Comment by kettle11** [comment]
This requires a bit more research, but I'll try to get to it soon. I do remember thinking it had to be this way, but it was a while ago now and maybe I was just tired. 😅

**Comment by lunabunn** [comment]
Pretty sure I just wasn't thinking straight. With the current implementation, because you only set the window after you create the context, you need to create a new window to set the correct PFD on. I'll close this 😅
