### ISSUE TITLE
Relicense to ZLib or Apache 2.0 or MIT

### ISSUE THREAD

**Issue by kettle11** [kettle11/kapp#63]
@lunabunn I know you said it in the chat, but just to get a record of it here, do you allow relicensing your changes as " ZLib or Apache 2.0 or MIT"?

**Comment by lunabunn** [comment]
Yup! Totally on board. 🚀

**Comment by kettle11** [comment]
Done in: b0418a86ee333341117160f443597b3877fc66a5
